export const SIMPLE_ICONS = ['github', 'x'];

export const LUCIDE_ICONS = [
    // 基本・デフォルト
    'brain',
    'refresh-cw',
    'atom',
    'shield-check',
    'pie-chart',
    'line-chart',
    'search',
    'x',
    'sun',
    'moon',
    'telescope',
    'sliders-horizontal',
    'rotate-cw',
    'arrow-left',
    'waves',
    // ビジネス・戦略
    'component',
    'layout-dashboard',
    'users-2',
    'gem',
    'swords',
    'link',
    'castle',
    'target',
    'briefcase',
    'list',
    'list-check',
    'calendar-check',
    // 思考・分析
    'columns-4',
    'rocket',
    'rotate-cw',
    'help-circle',
    'git-pull-request',
    'triangle',
    'skull',
    'test-tube-2',
    'grid-2x2',
    'grid-3x3',
    'columns-4',
    // システム・効率
    'network',
    'dumbbell',
    'map',
    'disc-3',
    'wrench',
    'recycle',
    'hourglass',
    // 確率・判断・心理
    'scale',
    'calculator',
    'trending-up-down',
    'trending-down',
    'bird',
    'door-open',
    'arrow-right-to-line',
    'eye-off',
    'microscope',
    'layers',
    'layers-3',
    'split',
    'arrow-left-right',
    'chart-scatter',
];